version: '3.4'

services:
  cqrssplitwise:
    image: ${DOCKER_REGISTRY-}cqrssplitwise
    build:
      context: .
      dockerfile: CQRSSplitWise/Dockerfile
    networks:
      - cqrsapp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    command: mongod --port 27018
    ports:
      - 27018:27018

networks:
    cqrsapp:
        driver: bridge