version: '3.4'

services:
  splitwise-command:
    image: ${DOCKER_REGISTRY-}cqrssplitwise.client.command
    build:
      context: .
      dockerfile: CQRSSplitWise.Client.Command/Dockerfile
    ports:
      - "5000:80"
    expose:
      - 5000
    depends_on:
      - mongo
      - sqldb
      - eventstore

  splitwise-query:
    image: ${DOCKER_REGISTRY-}cqrssplitwise.client.query
    build:
      context: .
      dockerfile: CQRSSplitWise.Client.Query/Dockerfile
    ports:
      - "5001:80"
    expose:
      - 5001
    depends_on:
      - mongo
      - sqldb
      - eventstore

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"

  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"

  eventstore:
    image: eventstore/eventstore:20.6.1-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DEV=True
    ports:
      - 2113:2113
      - 1113:1113