version: '3.4'

services:
  cqrssplitwise:
    image: ${DOCKER_REGISTRY-}cqrssplitwise
    build:
      context: .
      dockerfile: CQRSSplitWise/Dockerfile
    ports:
      - "5000:80"
    expose:
      - 5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"