version: '3.4'

services:
  cqrssplitwise:
    image: ${DOCKER_REGISTRY-}cqrssplitwise
    build:
      context: .
      dockerfile: CQRSSplitWise/Dockerfile
    ports:
      - "5000:80"
    expose:
      - 5000
    depends_on:
      - mongo
      - sqldb

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"